module.exports = {
  "PRODUCTS": [
    {"id":"nap-azul-celeste","teamSlug":"napoli","type":"especial","name":"Napoli Azzurro Celeste","price":49.9,"sizes":["S","M","L"]},
    {"id":"fra-azul-profundo","teamSlug":"selecao-franca","type":"especial","name":"França Azul Profundo","price":49.9,"sizes":["S","M","L"]},
    {"id":"ita-tracksuit-notte","teamSlug":"selecao-italia","type":"conjunto","name":"Itália Tracksuit Notte","price":69.9,"sizes":["S","M","L"]},
    {"id":"mon-conjunto-monegasco","teamSlug":"monaco","type":"conjunto","name":"AS Monaco Conjunto Monegasco","price":69.9,"sizes":["S","M","L"]},
    {"id":"psg-conjunto-paris-noite","teamSlug":"psg","type":"conjunto","name":"PSG Conjunto Paris à Noite","price":69.9,"sizes":["S","M","L"]},
    {"id":"ars-conjunto-coral","teamSlug":"arsenal","type":"conjunto","name":"Arsenal Conjunto Coral","price":69.9,"sizes":["S","M","L"]},
    {"id":"ars-casaco-rubro","teamSlug":"arsenal","type":"casaco","name":"Arsenal Casaco Rubro","price":59.9,"sizes":["S","M","L"]},
    {"id":"ars-casaco-celeste","teamSlug":"arsenal","type":"casaco","name":"Arsenal Casaco Celeste","price":59.9,"sizes":["S","M","L"]},
    {"id":"psg-rosa-paris","teamSlug":"psg","type":"especial","name":"PSG Rosa Paris","price":49.9,"sizes":["S","M","L"]},
    {"id":"psg-casaco-preto-cinza","teamSlug":"psg","type":"casaco","name":"PSG Casaco Preto e Cinza","price":59.9,"sizes":["S","M","L"]},
    {"id":"psg-branca-paris","teamSlug":"psg","type":"especial","name":"PSG Branca Paris","price":49.9,"sizes":["S","M","L"]},
    {"id":"mil-conjunto-rubro","teamSlug":"milan","type":"conjunto","name":"AC Milan Conjunto Rubro-Negro","price":69.9,"sizes":["S","M","L"]},
    {"id":"mil-conjunto-classico","teamSlug":"milan","type":"conjunto","name":"AC Milan Conjunto Clássico","price":69.9,"sizes":["S","M","L"]},
    {"id":"psg-casaco-capuz","teamSlug":"psg","type":"casaco","name":"PSG Casaco com Capuz","price":59.9,"sizes":["S","M","L"]},
    {"id":"ars-retro-granate","teamSlug":"arsenal","type":"retro","name":"Arsenal Retrô Granate","price":54.9,"sizes":["S","M","L"]},
    {"id":"fra-conjunto-azul-claro","teamSlug":"selecao-franca","type":"conjunto","name":"França Conjunto Azul Claro","price":69.9,"sizes":["S","M","L"]},
    {"id":"psg-casaco-fleece","teamSlug":"psg","type":"casaco","name":"PSG Casaco Fleece Claro","price":59.9,"sizes":["S","M","L"]},
    {"id":"psg-retro-vertical","teamSlug":"psg","type":"retro","name":"PSG Retrô Vertical","price":54.9,"sizes":["S","M","L"]},
    {"id":"ars-conjunto-marinho","teamSlug":"arsenal","type":"conjunto","name":"Arsenal Conjunto Marinho","price":69.9,"sizes":["S","M","L"]},
    {"id":"ars-casaco-vermelho","teamSlug":"arsenal","type":"casaco","name":"Arsenal Casaco Vermelho","price":59.9,"sizes":["S","M","L"]},
    {"id":"fra-conjunto-marinho","teamSlug":"selecao-franca","type":"conjunto","name":"França Conjunto Marinho","price":69.9,"sizes":["S","M","L"]},
    {"id":"ars-casaco-retro-marinho","teamSlug":"arsenal","type":"casaco","name":"Arsenal Casaco Retrô Marinho","price":59.9,"sizes":["S","M","L"]},
    {"id":"rom-conjunto-imperial","teamSlug":"roma","type":"conjunto","name":"Roma Conjunto Imperial","price":69.9,"sizes":["S","M","L"]},
    {"id":"ars-conjunto-preto-rubro","teamSlug":"arsenal","type":"conjunto","name":"Arsenal Conjunto Preto e Rubro","price":69.9,"sizes":["S","M","L"]},
    {"id":"laz-retro-azul-celeste","teamSlug":"lazio","type":"retro","name":"Lazio Retrô Azul Celeste","price":54.9,"sizes":["S","M","L"]},
    {"id":"ars-celeste","teamSlug":"arsenal","type":"especial","name":"Arsenal Celeste","price":49.9,"sizes":["S","M","L"]},
    {"id":"mil-conjunto-preto-vermelho","teamSlug":"milan","type":"conjunto","name":"AC Milan Conjunto Preto e Vermelho","price":69.9,"sizes":["S","M","L"]},
    {"id":"psg-branca-dourada","teamSlug":"psg","type":"especial","name":"PSG Branca Dourada","price":49.9,"sizes":["S","M","L"]},
    {"id":"ita-conjunto-verde","teamSlug":"selecao-italia","type":"conjunto","name":"Itália Conjunto Verde","price":69.9,"sizes":["S","M","L"]},
    {"id":"fio-violeta","teamSlug":"fiorentina","type":"especial","name":"Fiorentina Violeta","price":49.9,"sizes":["S","M","L"]},
    {"id":"ita-azul-ouro","teamSlug":"selecao-italia","type":"especial","name":"Itália Azul e Ouro","price":49.9,"sizes":["S","M","L"]},
    {"id":"int-riscas-nerazzurre","teamSlug":"inter","type":"especial","name":"Inter Riscas Nerazzurre","price":49.9,"sizes":["S","M","L"]},
    {"id":"ars-casaco-heritage","teamSlug":"arsenal","type":"casaco","name":"Arsenal Casaco Heritage","price":59.9,"sizes":["S","M","L"]},
    {"id":"nap-retro-celeste","teamSlug":"napoli","type":"retro","name":"Napoli Retrô Celeste","price":54.9,"sizes":["S","M","L"]},
    {"id":"ars-rubro-classica","teamSlug":"arsenal","type":"especial","name":"Arsenal Rubro Clássica","price":49.9,"sizes":["S","M","L"]},
    {"id":"mil-conjunto-preto","teamSlug":"milan","type":"conjunto","name":"AC Milan Conjunto Preto","price":69.9,"sizes":["S","M","L"]},
    {"id":"ita-azul-rubi","teamSlug":"selecao-italia","type":"especial","name":"Itália Azul Rubi","price":49.9,"sizes":["S","M","L"]},
    {"id":"esp-branca-ouro","teamSlug":"selecao-espanha","type":"especial","name":"Espanha Branca Dourada","price":49.9,"sizes":["S","M","L"]},
    {"id":"esp-conjunto-marfil","teamSlug":"selecao-espanha","type":"conjunto","name":"Conjunto Espanha Marfim Carmesim","price":69.9,"sizes":["S","M","L"]},
    {"id":"esp-kit-azul","teamSlug":"selecao-espanha","type":"conjunto","name":"Conjunto Espanha Azul Ibérica","price":69.9,"sizes":["S","M","L"]},
    {"id":"esp-tracksuit-celeste","teamSlug":"selecao-espanha","type":"conjunto","name":"Conjunto Espanha Fúria Celeste","price":69.9,"sizes":["S","M","L"]},
    {"id":"esp-casaco-marfil","teamSlug":"selecao-espanha","type":"casaco","name":"Casaco Espanha Marfim Clássico","price":59.9,"sizes":["S","M","L"]},
    {"id":"bar-conjunto-noite","teamSlug":"barcelona","type":"conjunto","name":"Conjunto Barça Noite Catalã","price":69.9,"sizes":["S","M","L"]},
    {"id":"fla-conjunto-imperial","teamSlug":"flamengo","type":"conjunto","name":"Conjunto Flamengo Nobreza Rubro-Negra","price":69.9,"sizes":["S","M","L"]},
    {"id":"bar-legacy-azulgrana","teamSlug":"barcelona","type":"retro","name":"Barça Legado Azulgrana","price":54.9,"sizes":["S","M","L"]},
    {"id":"esp-casaco-granate","teamSlug":"selecao-espanha","type":"casaco","name":"Casaco Espanha Herança Granate","price":59.9,"sizes":["S","M","L"]},
    {"id":"bar-infantil-blaugrana","teamSlug":"barcelona","type":"especial","name":"Barça Mini Blaugrana","price":44.9,"sizes":["S","M","L"]},
    {"id":"esp-casaco-neve","teamSlug":"selecao-espanha","type":"casaco","name":"Casaco Espanha Branca de Honra","price":59.9,"sizes":["S","M","L"]},
    {"id":"esp-furia-roja","teamSlug":"selecao-espanha","type":"especial","name":"Espanha Fúria Roja","price":49.9,"sizes":["S","M","L"]},
    {"id":"bar-casaco-blaugrana","teamSlug":"barcelona","type":"casaco","name":"Casaco Barça Cores da Catalunha","price":59.9,"sizes":["S","M","L"]},
    {"id":"por-sombra","teamSlug":"selecao-portugal","name":"Portugal Sombra Lusitana","price":54.9,"sizes":["S","M","L"],"type":"especial"},
    {"id":"ben-conjunto-rubro","teamSlug":"benfica","name":"Conjunto Benfica Raça Rubra","price":69.9,"sizes":["S","M","L"],"type":"conjunto"},
    {"id":"bra-guerreiros","teamSlug":"braga","name":"Braga Alma Guerreira","price":49.9,"sizes":["S","M","L"],"type":"especial"},
    {"id":"ben-conjunto-luz","teamSlug":"benfica","name":"Conjunto Benfica Luz Branca","price":69.9,"sizes":["S","M","L"],"type":"conjunto"},
    {"id":"ben-casaco-rubro","teamSlug":"benfica","name":"Casaco Benfica Voo Rubro","price":59.9,"sizes":["S","M","L"],"type":"casaco"},
    {"id":"fcp-brisa","teamSlug":"porto","name":"Porto Brisa do Douro","price":49.9,"sizes":["S","M","L"],"type":"especial"},
    {"id":"por-legado","teamSlug":"selecao-portugal","name":"Portugal Legado Lusitano","price":54.9,"sizes":["S","M","L"],"type":"retro"},
    {"id":"ben-imperial","teamSlug":"benfica","name":"Benfica Águia Imperial","price":54.9,"sizes":["S","M","L"],"type":"especial"},
    {"id":"sel-brisa-turquesa","teamSlug":"selecao","name":"Brasil Brisa Turquesa","price":49.9,"sizes":["S","M","L"]},
    {"id":"bot-estrelas","teamSlug":"botafogo","name":"Estrela Alvinegra","price":49.9,"sizes":["S","M","L"]},
    {"id":"bot-heranca","teamSlug":"botafogo","name":"Herança Gloriosa","price":54.9,"sizes":["S","M","L"]},
    {"id":"bah-azul","teamSlug":"bahia","name":"Azul da Bahia","price":49.9,"sizes":["S","M","L"]},
    {"id":"bah-branca","teamSlug":"bahia","name":"Branca de Salvador","price":49.9,"sizes":["S","M","L"]},
    {"id":"bah-retro","teamSlug":"bahia","name":"Tricolor de Aço Retrô","price":54.9,"sizes":["S","M","L"]},
    {"id":"rma-noite","teamSlug":"real-madrid","name":"Noite de Madrid","price":54.9,"sizes":["S","M","L"]},
    {"id":"sel-arte-urbana","teamSlug":"selecao","name":"Brasil Arte Urbana","price":49.9,"sizes":["S","M","L"]},
    {"id":"sel-ondas","teamSlug":"selecao","name":"Brasil Ondas Urbanas","price":49.9,"sizes":["S","M","L"]},
    {"id":"sel-casaco-perola","teamSlug":"selecao","name":"Casaco Brasil Pérola","price":59.9,"sizes":["S","M","L"],"type":"casaco"},
    {"id":"eng-casaco-neve","teamSlug":"inglaterra","name":"Casaco Inglaterra Neve","price":59.9,"sizes":["S","M","L"],"type":"casaco"},
    {"id":"eng-casaco-noite","teamSlug":"inglaterra","name":"Casaco Inglaterra Noturno","price":59.9,"sizes":["S","M","L"],"type":"casaco"},
    {"id":"sel-casaco-asfalto","teamSlug":"selecao","name":"Casaco Brasil Asfalto","price":59.9,"sizes":["S","M","L"],"type":"casaco"},
    {"id":"sel-casaco-salvia","teamSlug":"selecao","name":"Casaco Brasil Sálvia","price":59.9,"sizes":["S","M","L"],"type":"casaco"},
    { "id": "sel-branca-brasil", "teamSlug": "selecao", "name": "Branca do Brasil", "price": 49.9, "sizes": ["S","M","L"] },
    { "id": "sel-principal-24", "teamSlug": "selecao", "name": "Amarelinha da Copa", "price": 53.9, "sizes": ["S","M","L"] },
    { "id": "sel-alt-24", "teamSlug": "selecao", "name": "Azul da Copa", "price": 48.9, "sizes": ["S","M","L"] },
    { "id": "sel-especial-24", "teamSlug": "selecao", "name": "Amarelinha Classica", "price": 53.9, "sizes": ["S","M","L"] },
    { "id": "fla-principal-24", "teamSlug": "flamengo", "name": "Manto Rubro-Negro", "price": 53.9, "sizes": ["S","M","L"] },
    { "id": "fla-alt-24", "teamSlug": "flamengo", "name": "Manto Rubro-Negro Branco", "price": 48.9, "sizes": ["S","M","L"] },
    { "id": "fla-extra-24", "teamSlug": "flamengo", "name": "Manto Rubro-Negro diferenciado", "price": 53.9, "sizes": ["S","M","L"] },
    { "id": "cor-principal-24", "teamSlug": "corinthians", "name": "Fiel Alvinegra", "price": 53.9, "sizes": ["S","M","L"] },
    { "id": "cor-extra-24", "teamSlug": "corinthians", "name": "Fiel Alvinegra diferenciada", "price": 48.9, "sizes": ["S","M","L"] },
    { "id": "sao-principal-24", "teamSlug": "sao-paulo", "name": "Soberana Tricolor New Balance", "price": 62.9, "sizes": ["S","M","L"] },
    { "id": "sao-retro", "teamSlug": "sao-paulo", "name": "Soberana Tricolor", "price": 53.9, "sizes": ["M","L"] },
    { "id": "pal-principal-24", "teamSlug": "palmeiras", "name": "Verdão Classico", "price": 53.9, "sizes": ["S","M","L"] },
    { "id": "pal-retro", "teamSlug": "palmeiras", "name": "Verdão Retro", "price": 53.9, "sizes": ["M","L"] },
    { "id": "santos-principal-24", "teamSlug": "santos", "name": "Peixe Classico", "price": 53.9, "sizes": ["S","M","L"] },
    { "id": "santos-extra-24", "teamSlug": "santos", "name": "Peixe Diferenciado", "price": 44.9, "sizes": ["S","M","L"] },
    { "id": "cru-principal-24", "teamSlug": "cruzeiro", "name": "Manto Celeste Azul", "price": 44.9, "sizes": ["S","M","L"] },
    { "id": "cru-alt-24", "teamSlug": "cruzeiro", "name": "Manto Celeste Branco", "price": 48.9, "sizes": ["S","M","L"] },
    { "id": "por-alt-24", "teamSlug": "selecao-portugal", "name": "Azul de Portugal", "price": 44.9, "sizes": ["S","M","L"] },
    { "id": "por-principal-24", "teamSlug": "selecao-portugal", "name": "Vermelha de Portugal", "price": 46.9, "sizes": ["S","M","L"] },
    { "id": "ben-principal-24", "teamSlug": "benfica", "name": "Classica do Benfica", "price": 44.9, "sizes": ["S","M","L"] },
    { "id": "ben-extra-24", "teamSlug": "benfica", "name": "Diferenciada do Benfica", "price": 44.9, "sizes": ["S","M","L"] },
    { "id": "spo-principal-24", "teamSlug": "sporting", "name": "Classica do Sporting", "price": 47.9, "sizes": ["S","M","L"] },
    { "id": "spo-alt-24", "teamSlug": "sporting", "name": "Branca do Sporting", "price": 47.9, "sizes": ["S","M","L"] },
    { "id": "fcp-principal-24", "teamSlug": "porto", "name": "Classica do Porto", "price": 46.9, "sizes": ["S","M","L"] },
    { "id": "fcp-extra-24", "teamSlug": "porto", "name": "Diferenciada do Porto", "price": 44.9, "sizes": ["S","M","L"] }
  ],
  "PROMO_CONFIG": {
    "promotionEnabled": true,
    "promotionStart": "2026-09-18T00:00:00+01:00",
    "promotionEnd": "2026-10-09T23:59:59+01:00",
    "promotionTimeZone": "Europe/Lisbon",
    "eligibleProducts": [],
    "requiredQuantity": 6,
    "freeQuantity": 3,
    "maximumApplicationsPerOrder": 1
  },
  // Espelho de TIER_CONFIG em js/data.js — "Quanto mais levas, mais poupas".
  // Editar SEMPRE os dois ficheiros juntos (aqui e js/data.js) para os
  // escalões mostrados na página de produto baterem certo com o desconto
  // realmente cobrado no checkout.
  // "2 por 79 €" — espelho de PAIR_CONFIG em js/data.js (editar os dois juntos).
  // Só 1 par por encomenda; casacos excluídos; nunca soma com as outras promoções.
  "PAIR_CONFIG": {
    "enabled": true,
    "eligibleProducts": [],
    "excludedTypes": ["casaco", "conjunto"],
    "quantity": 2,
    "priceCents": 7900,
    "maximumApplicationsPerOrder": 1
  },
  "TIER_CONFIG": {
    "enabled": true,
    "eligibleProducts": [],
    "tiers": [
      { "threshold": 3, "pay": 2 },
      { "threshold": 6, "pay": 3 },
      { "threshold": 9, "pay": 4 },
      { "threshold": 12, "pay": 5 },
      { "threshold": 15, "pay": 6 }
    ]
  }
};
